services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quote_editor_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    environment:
      BUNDLE_PATH: /usr/local/bundle
      DATABASE_URL: postgres://postgres:postgres@db:5432/quote_editor_development
      DATABASE_URL_TEST: postgres://postgres:postgres@db:5432/quote_editor_test
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
      RAILS_ENV: development
  chrome:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2gb
    ports:
      - "4444:4444"

volumes:
  postgres_data:
  bundle:
